export const projects = [
  {
    id: 'sedra-1b',
    sector: 'residential',
    status: { en: 'PRE-QUALIFIED SUPPLIER', ar: 'مورد مؤهل مسبقًا' },
    name: { en: 'Riyadh Sedra Township — Phase 1B', ar: 'مشروع روشن سدرة الرياض — المرحلة 1ب' },
    meta: { en: 'ROSHN Group · HG Hanmi Global Saudi · Zuhaer A. Zahran & Co.', ar: 'روشن · إتش جي هانمي جلوبال · زهير زهران وشركاه' },
    scope: { en: 'Specialized mechanical supply & support', ar: 'توريد ودعم ميكانيكي متخصص' },
  },
  {
    id: 'wwtp-east',
    sector: 'water',
    status: { en: 'COMPLETED', ar: 'مكتمل' },
    name: { en: 'Wastewater Treatment Plant — Eastern Province', ar: 'محطة معالجة مياه الصرف — المنطقة الشرقية' },
    meta: { en: 'National Water Company · Main Contractor', ar: 'المياه الوطنية · مقاول رئيسي' },
    scope: { en: 'Pumps & odor control systems', ar: 'مضخات وأنظمة مكافحة الروائح' },
  },
  {
    id: 'retail-riyadh',
    sector: 'commercial',
    status: { en: 'IN PROGRESS', ar: 'قيد التنفيذ' },
    name: { en: 'Retail Centre — North Riyadh', ar: 'مركز تجاري — شمال الرياض' },
    meta: { en: 'Private developer', ar: 'مطور خاص' },
    scope: { en: 'Full-scope HVAC & commissioning', ar: 'تكييف كامل النطاق وتشغيل' },
  },
  {
    id: 'jubail-industrial',
    sector: 'industrial',
    status: { en: 'COMPLETED', ar: 'مكتمل' },
    name: { en: 'Industrial Facility — Jubail', ar: 'مجمع صناعي — الجبيل' },
    meta: { en: 'General contractor', ar: 'مقاول عام' },
    scope: { en: 'Industrial pumps, valves & control panels', ar: 'مضخات صناعية وصمامات ولوحات تحكم' },
  },
  {
    id: 'jeddah-compound',
    sector: 'residential',
    status: { en: 'COMPLETED', ar: 'مكتمل' },
    name: { en: 'Residential Compound — Jeddah', ar: 'مجمع سكني — جدة' },
    meta: { en: 'Private developer', ar: 'مطور خاص' },
    scope: { en: 'Pump rooms & firefighting systems', ar: 'غرف مضخات ومكافحة الحرائق' },
  },
  {
    id: 'qassim-irrigation',
    sector: 'water',
    status: { en: 'IN PROGRESS', ar: 'قيد التنفيذ' },
    name: { en: 'Irrigation Network — Qassim', ar: 'شبكة ري — القصيم' },
    meta: { en: 'Government authority', ar: 'جهة حكومية' },
    scope: { en: 'Irrigation pumps & flow meters', ar: 'مضخات ري وعدادات تدفق' },
  },
  {
    id: 'khobar-tower',
    sector: 'commercial',
    status: { en: 'COMPLETED', ar: 'مكتمل' },
    name: { en: 'Office Tower — Khobar', ar: 'برج مكاتب — الخبر' },
    meta: { en: 'Main contractor', ar: 'مقاول رئيسي' },
    scope: { en: 'MEP design & balancing', ar: 'تصميم كهروميكانيكي وموازنة' },
  },
  {
    id: 'riyadh-food',
    sector: 'industrial',
    status: { en: 'COMPLETED', ar: 'مكتمل' },
    name: { en: 'Food Processing Plant — Riyadh', ar: 'مصنع أغذية — الرياض' },
    meta: { en: 'Private owner', ar: 'مالك خاص' },
    scope: { en: 'Sanitary pumps & instrumentation', ar: 'مضخات صحية وأجهزة قياس' },
  },
  {
    id: 'makkah-lifting',
    sector: 'water',
    status: { en: 'IN PROGRESS', ar: 'قيد التنفيذ' },
    name: { en: 'Water Lifting Station — Makkah', ar: 'محطة رفع مياه — مكة' },
    meta: { en: 'Government authority', ar: 'جهة حكومية' },
    scope: { en: 'Pumps & control panels', ar: 'مضخات ولوحات تحكم' },
  },
];

export const PAGE_SIZE = 6;
